---
####### Docker Config: pull secret for internal registry
- name: '{{ ansible_name_module }} | copy | Place Registry Pull Secret to {{ dir_secrets }}/docker/config.json'
  copy:
    dest: "{{ dir_secrets }}/docker/config.json"
    content: '{"auths": {"registry.{{ cluster_domain }}:5000": {"auth": "{{ "cloudctl:cloudctl" | b64encode }}","email": "admin@{{ name_domain }}" } } }'
    mode: '0644' # TODO: Figure out the correct permissions

- name: '{{ ansible_name_module }} | copy | Place Registry Pull Secret to ~/.docker/config.json'
  copy:
    dest: "{{ local_home }}/.docker/config.json"
    content: '{"auths": {"registry.{{ cluster_domain }}:5000": {"auth": "{{ "cloudctl:cloudctl" | b64encode }}","email": "admin@{{ name_domain }}" } } }'
    mode: '0644' # TODO: Figure out the correct permissions
