---
- name: '{{ ansible_name_module }} | ssh | file:directory | Create Directory Structure'
  file:
    path: '{{ item }}'
    state: directory
    mode: '0644'
  with_items:
    - '{{ dir_secrets }}/ssh'

- name: '{{ ansible_name_module }} | ssh | openssh_keypair | Generate Deployment Keys'
  openssh_keypair:
    path: "{{ dir_secrets }}/ssh/id_rsa_kubeadmin"
    comment: "core@ocp.kubeadmin"
