#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ name_vendor }} | Konductor | secrets.yml'
  hosts: local
  vars_files:
    - '../cluster-vars.yml'
#   - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
#   - 'vars/git.yml'
  vars:
    module: "secrets"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - secrets
