#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | Konductor | template'
  hosts: local
  vars_files:
    - '../cluster-vars.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
#   - 'vars/git.yml'
  vars:
    module: "template"
    state_provider: "{{ terraform_state_provider }}"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    dir_platform_templates: "{{ dir_iac }}/openshift/templates"
    tmpl_installconfig_j2: "{{ dir_platform_templates }}/openshift-install/{{ cloud_provider }}-{{ target_environment }}-install-config.yaml.j2"
    cloud_key_id_special: "{{ lookup('ini', 'aws_access_key_id section=default file={{ dir_secrets }}/aws/credentials') }}"
    cloud_key_secret_special: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ dir_secrets }}/aws/credentials') }}"
    redhat_quay_pull_file: '{{ dir_secrets }}/docker/config.json }}'
  tasks:
    ####### Ignition User Data
    - name: '{{ ansible_name_module }} role | manifests | template | Stage OpenShift Ignition User-Data JSON'
      template:
        src: "{{ dir_platform_templates }}/user-data/user-data-ign.json.j2"
        dest: "{{ dir_platform }}/config/user-data/{{ item.name }}.json"
        mode: '0644' # TODO: Figure out the correct permissions
      with_items:
        - { name: master,    IGNITION_URL:  "http://registry.{{ cluster_domain }}/master.ign" }
        - { name: bootstrap, IGNITION_URL:  "http://registry.{{ cluster_domain }}/bootstrap.ign" }
        - { name: bastion,   USER_AUTH_KEY: "{{ lookup('file', '{{ dir_secrets }}/ssh/id_rsa_kubeadmin.pub') }}" }

    - name: '{{ ansible_name_module }} role | manifests | template | Stage OpenShift Ignition User-Data B64'
      template:
        src: "{{ dir_platform_templates }}/user-data/user-data-ign.b64.j2"
        dest: "{{ dir_platform }}/config/user-data/{{ item.name }}-json.b64"
        mode: '0644' # TODO: Figure out the correct permissions
      with_items:
        - { name: 'master',    IGNITION_URL: "http://registry.{{ cluster_domain }}/master.ign" }
        - { name: 'bootstrap', IGNITION_URL: "http://registry.{{ cluster_domain }}/bootstrap.ign" }
        - { name: 'bastion',   USER_AUTH_KEY: "{{ lookup('file', '{{ dir_secrets }}/ssh/id_rsa_kubeadmin.pub') }}" }
