---
####### Detect manifest random id name
- name: '{{ ansible_name_module }} | shell:awk | Get cluster random name'
  shell: "awk -F'[-]' '/infrastructureName/{print $NF}' {{ dir_platform }}/cluster/manifests/manifests/cluster-infrastructure-02-config.yml"
  register: idrand
  ignore_errors: True
  no_log: True

####### replace manifest random id name
- name: '{{ ansible_name_module }} | replace | s/randId/vpcName/g'
  replace:
    path: "{{ dir_platform }}/cluster/manifests/manifests/cluster-infrastructure-02-config.yml"
    regexp: "infrastructureName: {{ cluster_name }}-{{ idrand.stdout }}"
    replace: "infrastructureName: {{ name_cluster_vpc }}"
  no_log: True
  ignore_errors: True

####### Itemize all manifest files
- name: '{{ ansible_name_module }} | find |  Find all manifest files'
  find:
    path: "{{ dir_platform }}/cluster/manifests"
    recurse: yes
    age: 1s
  register: manifests

####### Replace infrastructure name across all manifests
- name: '{{ ansible_name_module }} | replace | Replace infrastructureName for all files'
  replace:
    path: "{{ item.path }}"
    regexp: "{{ cluster_name }}-{{ idrand.stdout }}"
    replace: "{{ name_cluster_vpc }}"
  no_log: True
  loop: "{{ manifests.files }}"

####### Remove Ingress Controller
- name: '{{ ansible_name_module }} | Remove | Remove Ingress Controller'
  file:
    path: "{{ dir_platform }}/cluster/manifests/manifests/cluster-ingress-default-ingresscontroller.yaml"
    state: absent
  when: external_ingress == 'true'

####### Remove Publish Internal
- name: '{{ ansible_name_module }} | Remove | Remove Publish: Internal'
  lineinfile:
    path: "{{ dir_platform }}/cluster/manifests/manifests/cluster-config.yaml"
    state: absent
    regexp: '^publish: Internal'
  when: external_ingress == 'true'

####### Remove privateZone from cluster DNS config
- name: '{{ ansible_name_module }} | replace | Remove privateZone'
  replace:
    path: "{{ dir_platform }}/cluster/manifests/manifests/cluster-dns-02-config.yml"
    regexp: '^\s\sprivateZone[^&]+'
    replace: '' 
