---
- name: '{{ ansible_name_module }} | file:absent | Purge pre-existing artifacts'
  file:
    path: '{{ dir_platform }}/cluster/ignition'
    state: absent

- name: '{{ ansible_name_module }} | file:directory | Purge pre-existing artifacts'
  file:
    path: '{{ dir_platform }}/cluster/ignition'
    state: directory
    mode: '0755'

- name: '{{ ansible_name_module }} | copy | Load manifests into ignition directory'
  copy:
    src: "{{ dir_platform }}/cluster/manifests/"
    dest: "{{ dir_platform }}/cluster/ignition/"
    mode: '0644'

- name: '{{ ansible_name_module }} | command:openshift-install | Generate ignition config files'
  command: "{{ openshift_install_binary }} create ignition-configs --dir={{ dir_platform }}/cluster/ignition"
