---
####### Stage ~/.docker/config.json
- name: '{{ ansible_name_module }} | file | Docker Pull Secrets Dir'
  file:
    path: "{{ dir_secrets }}/docker"
    state: directory
    mode: '0755'

- name: '{{ ansible_name_module }} | copy | Save Quay.io Pull Secret to {{ dir_secrets }}/docker/quay.json'
  copy:
    src: "/root/.docker/config.json"
    dest: "{{ dir_secrets }}/docker/quay.json"
    mode: '0600'
