#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | secrets.yml'
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
    - 'vars/images.yml'
    - 'vars/git.yml'
  vars:
    module: "secrets"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - secrets
